# Generated by Django 4.2.6 on 2024-03-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateField(verbose_name='Дата въезда'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateField(verbose_name='Дата выезда'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='occupancy',
            field=models.PositiveSmallIntegerField(verbose_name='Вместимость'),
        ),
    ]
